"""Regenerate fixtures with NumPy/SciPy; runtime tests do not require Python.

Reference: ECGFounder util.filter_bandpass at revision
04edac702b61c91face519774ddcc0cd712fef23, evaluated at 500 Hz after anti-aliased decimation from 2,000 Hz and followed by population z-score.
"""
import json
from pathlib import Path
import numpy as np
import scipy
from scipy.signal import butter, filtfilt, iirnotch, medfilt, resample_poly, firwin, lfilter_zi

cases = {}
i = np.arange(24000, dtype=np.float64)
sample_rate = 2000
model_rate = 500
baseline_samples = 201
t = i / sample_rate
cases['periodic'] = np.sin(2 * np.pi * 1.2 * t) + 0.2 * np.sin(2 * np.pi * 12 * t)
cases['baseline_and_interference'] = (
    np.sin(2 * np.pi * 1.2 * t) + 0.3 * np.sin(2 * np.pi * 50 * t)
    + 512 + 0.3 * np.sin(2 * np.pi * 490 * t) + 0.5 * np.sin(2 * np.pi * 0.2 * t)
    + np.where(i % 1664 == 0, 2.0, 0.0)
)
fixtures = []
for name, signal in cases.items():
    resampled = resample_poly(signal, 1, 4)
    filtered = filtfilt(*iirnotch(50, 30, model_rate), resampled)
    filtered = filtfilt(*butter(4, [0.67, 40], btype='bandpass', fs=model_rate), filtered)
    filtered -= medfilt(filtered, kernel_size=baseline_samples)
    expected = ((filtered - filtered.mean()) / (filtered.std() + 1e-8)).astype(np.float32)
    fixtures.append(dict(name=name, samples=signal.tolist(), resampled=resampled.tolist(), expected=expected.tolist()))
destination = Path(__file__).parent / 'fixtures/ecg-preprocessing.json'
destination.parent.mkdir(exist_ok=True)
destination.write_text(json.dumps(dict(scipy=scipy.__version__, numpy=np.__version__, sample_rate=sample_rate, model_rate=model_rate, baseline_samples=baseline_samples, cases=fixtures)), encoding='utf-8')
print(f'Wrote {destination}')

def pack(pair):
    b, a = pair
    return dict(b=b.tolist(), a=a.tolist(), zi=lfilter_zi(b, a).tolist())

coefficients = '// Generated by tests/generate-ecg-reference.py using SciPy. Filtering runs at 500 Hz.\n'
for name, value in [
    ('notch', pack(iirnotch(50, 30, model_rate))),
    ('bandpass', pack(butter(4, [0.67, 40], btype='bandpass', fs=model_rate))),
    ('decimation', firwin(81, .25, window=('kaiser', 5)).tolist()),
]:
    coefficients += f'export const {name} = {json.dumps(value)};\n'
(Path(__file__).resolve().parents[1] / 'src/lib/ecg-filter-coefficients.ts').write_text(coefficients, encoding='utf-8')
